### PR TITLE
Last air date

### PR DESCRIPTION
**Pull request by da3dsoul**
I really don't know why my VS2015 hates making whitespace look right. It looks okay in the editor...

### CODE REVIEW

**Comment by da3dsoul** [comment]
requires https://github.com/japanesemediamanager/jmmserver/pull/249

**Comment by da3dsoul** [comment]
https://github.com/japanesemediamanager/jmmclient/issues/313

**Comment by jmediamanager** [comment]
Gah, I can't automatically merge this one

**Comment by da3dsoul** [comment]
I'll fix it...

**Pull request merged**
