### PR TITLE
Fix for issues #31, #40, #61, #124, #263, #291, #331, #355

### PR DESCRIPTION
**Pull request by Rand-Random**
(My first pull request so sorry if I did something wrong, picked some backlog for my first one)

Had a look into 
https://github.com/japanesemediamanager/jmmclient/issues/31

Hope its okay what I did, not sure if its okay that I simply called the BeginInvoke instead of using some backgroundworker to do the job, and I kinda missused the 

MainListHelperVM.Instance.LastGroupForGF for an AnimeSeriesVM instead of a group but I believe thats okay since in the collection view there is a mixture between AnimeGroupVMs and AnimeSeriesVMs and the method

_HighlightMainListItem_

only highlighted the last selected AnimeGroupVM with the existing code.

### CODE REVIEW

**Comment by Rand-Random** [comment]
The changes indicator seems pretty f**ed up, saying +3,012 and -3,007, I only added 3 lines of code maybe 2-3 more with spacing, any idea what I did wrong?!?

**Comment by Rand-Random** [comment]
Figured out who did the f**ed up changes not sure why though...
It happens when Visual Studio 2015 auto formats the code, so when I hit the keys CTRL + K + D it changes the whole file not sure what it changes actually seems like whitespaces or line breaks.

Sorry for that.

**Comment by Rand-Random** [comment]
#40 was pretty hard to find, but I believe I found the root cause
it happened when you pinned a series and in some occasions the pinned page got a new object of animeseriesvm which didn't get updated correct (for example it happend when you pinned the series from the playlist)

in the fix I took the instance of the dictionary AllSeriesDictionary
also there was a problem in the metro view where the previous episode always had the wrong unwatched icon (its previous so its always watched instead of unwatched)

as discussed with @craige1 I did two commits the first to fix the indent issue and than a commit for the actual work sadly I couldnt figure out how to do the fix in a separate pull request so I followed @ElementalCrisis advice and commented the commit with the issue its supposed to fix

**Comment by Rand-Random** [comment]
There was still a problem

Open JMM Desktop
GoTo Playlist
Pin a series
Look at episodes
click tab collection
go back to pinned 
mark episode as watched 
= broken

the problem was that upon clicking the tab collection the method RefreshGroupsSeriesData gets called this initializes a new set of AnimeSeriesVM objects and clears the lists AllSeries and stuff.

So there were again multiple instances of the same series.
To fix this I did an event called "Refreshed", in the MainWindow.xaml.cs I listen to this event and upon firing I refresh the Pinned and Playlist Objects.

Btw, my changes may also fix #330 maybe @bigretromike can verify it.

**Comment by Rand-Random** [comment]
fixed #61, I also remove the visibility in the delete button in EpisodeDetail since it doesnt matter if the file exists or not since the delete will be issued to the server and it could exist on server side hope thats okay for you

**Comment by Rand-Random** [comment]
fixed #124

**Comment by Rand-Random** [comment]
fixed #263

**Comment by Rand-Random** [comment]
fixed #291

**Comment by Rand-Random** [comment]
fixed #331

**Comment by jmediamanager** [comment]
Thanks a lot @Rand-Random 
I'm trying to review a lot of the PR's over the next couple of days.

The problem with the spacing is probably because of the below screenshot
I use a space indent, because it has always been the standard at my work place.
I'm not sure what the default is, but it is probably a 2 space indent (or maybe your is set to this at least)

image

**Comment by Rand-Random** [comment]
@jmediamanager np
Your image are the default values, and the values I am using
maybe someone else has different settings

@maxpiva 
said the following in the discord chat
"JMMServer next change will change every f**ing file, because i just used Resharper -> Code Cleanup -> Reformat Code, and reidented with tabs the whole project, will do the same on JMMClient.
After that, any commit, should be using tabs instead of whitespaces. Otherwise it'll be rejected."

saying that he will update all files with a common indent which is good for me, and I don't care if its tab or whitespaces (he mentions it will be tabs, which isn't the default in VS maybe he mixed them up but as I said I wouldn't mind adjusting to that as long its so in all files)
its just that currently its a mixture of both, so no matter what setting I pick it always resolved in alot of changes and I had to be careful

**Pull request merged**
