### PR TITLE
Auto watched state MPC HC Web UI integration. #55

### PR DESCRIPTION
**Pull request by Daemeron**
JMMClient can now set watched state real time while watching using MPC HC Web UI functionality. By doing so we are not limited by any number of episodes on playlist nor any action needs to be taken. Hope you will like it.

Refers to #55 .

### CODE REVIEW

**Comment by Daemeron** [comment]
With latest commit giving ability to make a choice between ini integration and web ui integration this solution should be ready to use.

If there is something wrong with it or perhaps You have an idea how to improve it, please let me know.

**Comment by da3dsoul** [comment]
@Daemeron this needs updated to be merged.

**Comment by Daemeron** [comment]
Alright I'll take care of it.

**Comment by Daemeron** [comment]
Sorry I don't know how notifications works like here. Do I have to bump pull request to let owner know I merged and commits are ready to merged to main repository?

**Comment by ElementalCrisis** [comment]
Nope, just by updating it @jmediamanager will receive a notification. Thanks for updating your PR, it makes it a lot easier for us. :)

**Comment by Daemeron** [comment]
Is there anything I can do to improve this feature? Perhaps UI part of turning feature on or switching between ini integration? Or maybe feature itself needs some refining I am not aware on. Anybody have/had time to check it out?

**Comment by ElementalCrisis** [comment]
You can add any features you'd like if you think it will benefit users. :)

@jmediamanager approves all PR and he's been a bit busy lately, hopefully he gets some free time soon. 

Feel free to join us on Discord to talk with some of the other Devs and contributors if you'd like. :)

**Comment by craige1** [comment]
I've taken a look at this code but it doesn't seem to actually solve the #55 issue. Issue 55 is about letting jmm mark an episode as watched when it didn't start the episode directly. Given example is the player is started, and you watch the next episode and the next, etc without re-launching the player. The code you provided will only mark the episode that jmm started as watched and not any future episodes, and jmm already does this. The main issue is with line 235 in VideoHandler.cs, as it only runs the code for marking as an episode as watched against episodes jmm started itself.

**Comment by Daemeron** [comment]
Please provide me with with a code fragment instead of line which can change based on commits.

As far as I understood issue #55  the biggest issue with current solution is that how mpc-hc handles ini file. Problem is that ini file is updated when closing player or using player controls manually by clicking on video file timeline for example. That gives some inconveniences like big lag when closing player after watching multiple episodes or having a limit of tracking 20 episodes only. 

My approach fixes that issues.

Issue #55 have 3 key problems mentioned:

1. JMMDesktop get unresponsive when multiple files are updated. My feature is basically a service that runs real time after initial click on play ep or play all unwatched eps and updates file status while you watch. You will never get that behavior as file will me marked watched while you watch, not when you interact with a player controls or close mpc-hc. You will not even notice when it will be set as watched. Unless you can watch several files in 1 second in 1 instance of player.
2. When not closing the player while switching the animes/playlists - JMMDesktop starts doesnt know that I have watched something and restarts files that already been watched. My featuer dont care whenever you change playlist as it is service setting files state in real time. You can watch full 12 ep series without even touching a player after initializing playlist with JMMDesktop, then go back to JMMDesktop to press play all unwatched on different anime title and still have the same experience as before, files will be market watched as you watch them.
3. When playing more files then the max length of the players history JMMDesktop cant set them all because the players history doesnt list the file anymore (MPC has a limit of 20... My feature don't care for the amount of episodes you will have on your playlist. Go ahead and start watching Bleach from the very first episode having all XXX of them on your playlist and service will stay with you till the the last ep consequently setting files as watched as you enjoy epic episodes and get pissed at fillers...

You see JMMDesktop stores episodes you play from it whenever its one or multiple in memory. My service traverse them almost every second to find match with currently played episode and checks its progress.

Of course making it even mark files as you don't event star them from JMMDesktop itself is entirely possible but it would be slower then this one, depending on approach consume more memory and I can't stop to wonder, why would that even be needed. Ain't we using JMMDesktop front door to our collections so we don't have to locate files on hard drive and start them or manually make playlists?

**Comment by Daemeron** [comment]
Thank you for merging my fork with upstream. I did not have time to do it yesterday.

**Comment by ElementalCrisis** [comment]
Thanks for the contributions! :)

**Pull request merged**
