### PR TITLE
Update Website Links And Added Logs Notice

### PR DESCRIPTION
**Pull request by ElementalCrisis**
Changed links to reflect documentation, added a notice to the logs section about wait time, increased series window in unrecognized files.

I increased the series window in unrecognized files because for me it's always been really small. I don't know what the default window size JMM Desktop is so I did not increase it by much but ideally I'd like to make it bigger.

### CODE REVIEW

**Comment by ElementalCrisis** [comment]
Before Scrollviewer
jmmd-random without scrollbar

With Scrollviewer
jmmd-random with scrollbar

I'm sure there's a better way to fix this but it's probably a bit beyond my beginner skills.

**Comment by jmediamanager** [comment]
Yeah this is probably better done with a wrap panel.
I'll take a look at it later

**Comment by ElementalCrisis** [comment]
No worries, I'll see if I can fix it with a wrap panel later tonight. Allows me to learn new things.

**Comment by ElementalCrisis** [comment]
jmmd-random with wrap panel

I agree it looks better and I doubt anyone would ever use more than 20 tags, let alone 72 like in the image.

**Comment by jmediamanager** [comment]
Yup looks better.
Note - One thing that can also be done is to add spacing between the commas, so that the two words are not treated as a single word in the wrapping.

**Comment by ElementalCrisis** [comment]
OK, I'll do that and submit a commit.

**Pull request merged**
