### PR TITLE
 Random Series/Episode, Community and Group Filter

### PR DESCRIPTION
**Pull request by ElementalCrisis**

### CODE REVIEW

**Comment by ElementalCrisis** [comment]
Forgot to mention I also fixed #231.

**Comment by jmediamanager** [comment]
I'll do a full review later, but looks mostly good.

A couple of Notes

- In Community Admin, you have named the tab 'TvDB' but it could actually be TvDB / Trakt / etc
- For the Group Filter list you have hard coded the length/width of the list box which is something I generally try to avoid where possible. The better way to do this is to wrap it in a <ScrollViewer> which will make it look a bit nicer (e.g. the Episode list for a series)

I'll probably take a full look tomorrow and make those minor adjustments mentioned above

**Comment by ElementalCrisis** [comment]
I'll take a look and see if I can make those changes, these things are minor and I'm sure you've got more important tasks to handle. My only question is what would the preferred tab name be? I could change it to TvDB/Trakt or simply Other.

**Comment by AreFinstad** [comment]
how about Source Tab and Compare Tab? i mean AniDB will always be the Source every time (till there is support the other way) and all the other sites you open up is just to compare it either way.

**Comment by ElementalCrisis** [comment]
Done. :)

**Comment by jmediamanager** [comment]
Cool, don't forget that if you are fixing issues you can also update the changes page

**Comment by ElementalCrisis** [comment]
I've edited the updates page as well as some others and will upload them soon. I also made the changes to  the tab names but I was unable to make the changes to the Group Filter list for the width and height. I'll take a look at what you change so I know for future use.

**Comment by ElementalCrisis** [comment]
Noticed the folder location button was not available in the server tab, so I added it. Fixed filter spacing so words no longer touch a comma.

**Comment by ElementalCrisis** [comment]
When you make the changes to the filter preview, take a look at filter conditions because I also hard-coded the width to match the filter preview so it wouldn't stretch across the window.

**Comment by jmediamanager** [comment]
Ok I have just made a change to put the Grid-Splitter back in and removed some of the offsets you used.
Generally I think that if you need to do something like Margin="2,258,10,0" (a very large offset), it is an indication something is not quite right.

**Comment by jmediamanager** [comment]
Ok the reason I didn't have the folder selection on the Import Folder is that the server will not always be running on the same machine as Desktop.
So if you select a local folder on desktop, it might exist when the Server tries to scan it.

I have another issue somewhere, which is to implement this via a proxy through JMM server, which provides a list of folders that the server can see.

Until then, this probably needs to be removed

**Comment by jmediamanager** [comment]
Changes:

Used scroll viewer on Group Filter preview
Enabled mouse scrolling

**Comment by ElementalCrisis** [comment]
Yeah that was from using the Designer to move the tab panel up. I've since learned that grids are a much better option. As for the folder selection, that thought never crossed my mind, sorry about that. I'll go ahead and remove it.

**Comment by jmediamanager** [comment]
Yup WPF can be a bit of a learning curve

**Comment by ElementalCrisis** [comment]
Yeah, I've probably broke JMM Desktop a couple dozen times now. Do you have any recommendations on learning materials?

**Comment by jmediamanager** [comment]
I have always just googled everything :)

**Comment by ElementalCrisis** [comment]
The solution for any problem, googling.

**Pull request merged**
